echo " cp /down/import.sh ./"
echo "mount /dev/sr0 /mnt/"
echo "nano import.sh"
echo "chmod +x import.sh && bash import.sh"
echo " Zahod B ADMC na hq-cli"
echo " Login:Administrator Password:P@ssw0rd"
echo " Esli ne zahod, idi v terminal pishi:"
echo "kinit Administrator"
echo " zatem izmeni password na P@ssw0rd1 esli zaprosit"